### PR TITLE
Upgrade to Spring Framework 6 and Spring Boot 3

### PR DESCRIPTION
**Pull request by jspetrak**

### CODE REVIEW

**Comment by jspetrak** [comment]
Hello @georgwittberger, if you maintain this repository, I am providing this patch to upgrade the library to the latest Spring&Spring Boot.

**Comment by georgwittberger** [comment]
Hi @jspetrak , I appreciate your initiative to modernize this library. What a fantastic work! Unfortunately, I cannot maintain this project anymore. If you would like to continue working on this library I can transfer the repo to your account. You can publish the Maven artifact for your updated version using your own group ID anyway (even from your own repo).

**Comment by jspetrak** [comment]
Hello @georgwittberger I understand the reasons. Thank you for the offer. I am able to provide further maintenance of the project via our company resources. If you agree, please transfer the repository to @bileto. I will merge it and publish from there.

Thank you.

**Comment by georgwittberger** [comment]
Hi @jspetrak , sounds great. I've just tried to transfer this repo to your organization but it fails because I am not allowed to create public repos there. My suggestion is that I transfer the repo to your personal account first and then you can plug it into your organization from there. OK?

**Comment by jspetrak** [comment]
@georgwittberger Agreed. Thank you.

**Comment by georgwittberger** [comment]
@jspetrak , that does not work either because `jspetrak/extend-mdc` already exists, since you forked this repo to your own account. 😆 Could you rename your forked repo, so that `extend-mdc` becomes available as a repo name again?

**Comment by jspetrak** [comment]
@georgwittberger Oh :D I have changed the name.

**Comment by georgwittberger** [comment]
@jspetrak , this is getting weird. 😆 Even after you renamed your repo GitHub still complains about your account already having a repo named `extend-mdc` in the network. This makes sense to me because GitHub seems to preserve old names and redirects users to the new repo URLs.

I have tried renaming my repo to `extend-mdc-java-aspect` and attempted to transfer that to your account. But GitHub says: `jspetrak already has a repository in the georgwittberger/extend-mdc-java-aspect network` 😧 So it seems like it created that new alias for your fork as well.

Any ideas how to make that transfer work? 😉

**Comment by georgwittberger** [comment]
Maybe you could save the work on this PR locally, then delete your fork on GitHub. Then we could transfer this repo to your account and you can apply your saved work again in that transferred repo?

**Comment by jspetrak** [comment]
I have just done that and noted that at #2

**Pull request merged**
